export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/.rbenv/shims:$PATH
export SHELLFILES=$HOME/.shell_scripts
export EDITOR='vim'
export LANG=en_US.UTF-8

ZSH_THEME="spaceship"

plugins=(
  git
  ruby
  zsh-syntax-highlighting
  zsh-autosuggestions
  zsh-completions
)

source $ZSH/oh-my-zsh.sh
source $HOME/.aliases
source $SHELLFILES/development_test.sh
source $SHELLFILES/rails_server_helper.sh
source $ZSH/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

SPACESHIP_PROMPT_ORDER=(
	user          # Username section
	dir           # Current directory section
	host          # Hostname section
	git           # Git section (git_branch + git_status)
	hg            # Mercurial section (hg_branch  + hg_status)
	exec_time     # Execution time
	line_sep      # Line break
	vi_mode       # Vi-mode indicator
	jobs          # Background jobs indicator
	exit_code     # Exit code section
	char          # Prompt character
)
SPACESHIP_USER_SHOW=always
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "

eval "$(rbenv init -)"
